Adding Quick Setup option
1Axen/Secure-Cast pull request #4
Opened 2024-08-19 20:51 UTC by KendallCole

Option to programmatically create the nessasary folders instead of having to manually add them

2024-08-24 08:04 UTC, 1Axen commented on src/Utility/QuickSetup.lua
> +        Characters.Name = "Characters"
Characters folder should use the name specified in settings (`CharacterFolder`).

2024-08-24 08:04 UTC, 1Axen commented on src/Utility/QuickSetup.lua
> +    assert(workspace.Characters:IsA("Folder"), ERR_MSG)
Same thing here.

2024-08-24 08:08 UTC, 1Axen commented on src/Utility/QuickSetup.lua
> +function QuickSetup:Run()
Small nit, would prefer dot index instead of colon here, it's just more inline with the rest of the code.

2024-08-24 08:08 UTC, 1Axen commented on src/init.lua
> +        local QuickSetupUtility = require(Utility.QuickSetup)
Require should be moved out of here and into the imports section.

2024-08-24 08:09 UTC, 1Axen requested changes
I've left some comments on things that need changing before merging.

2024-08-25 17:02 UTC, KendallCole commented
Made the requested changes <3

2024-08-25 17:09 UTC, 1Axen commented on src/init.lua
> +local SnapshotsUtility = require(Utility.Snapshots)
I only meant for the `QuickSetupUtility` to be moved, moving the rest will cause them to error as they expect the characters and or visuals folder to exist which someone using the quick setup option might not have statically in their workspace.

2024-08-25 17:10 UTC, 1Axen requested changes
Breaking change needs resolving otherwise LGTM

2024-08-25 23:23 UTC, KendallCole commented
Made the change :)

2024-08-26 18:35 UTC, 1Axen approved these changes

2024-08-26 18:35 UTC, 1Axen commented
LGTM

2024-08-26 18:35 UTC, merged